language: c

compiler:
  - clang
  - gcc

script:
  - mkdir build && cd build && ./configure && make -j2 V=1
  - mkdir build && cd build && cmake .. && make -j2 VERBOSE=1

branches:
  only:
    - travis
